version: "2"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - influxdb-telegraf-net
    volumes:
      - influxdb-volume:/vol01/Docker/monitoring
  influxdb_cli:
    links:
      - influxdb
    image: influxdb
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    container_name: telegraf
    networks:
      - influxdb-telegraf-net
    links:
      - influxdb
    restart: always
    depends_on:
      - influxdb_cli
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_ORG=${INFLUX_ORG}
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
networks:
  influxdb-telegraf-net:
volumes:
  chronograf-volume:
    external: true
  influxdb-volume:
    external: true
  kapacitor-volume:
    external: true
